### ISSUE TITLE
Subscription Source in Hack is incorrect

### ISSUE THREAD

**Issue by cmwylie19** [rhobs/observability-operator#156]
The subscription source in `/hack/olm/subscription.yaml` should be `observability-operator`

**Comment by cmwylie19** [comment]
The way that I got the operator installed and working can be found per this block:
```yaml
oc apply -f -<<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
  name: observability-operator
  namespace: openshift-marketplace
spec:
  displayName: Observability Operator - Test
  icon:
    base64data: ""
    mediatype: ""
  image: quay.io/rhobs/observability-operator-catalog:latest
  publisher: Sunil Thaha
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 1m0s
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/observability-operator.openshift-operators: ""
  name: observability-operator
  namespace: openshift-operators
spec:
  channel: development
  installPlanApproval: Automatic
  name: observability-operator
  source: observability-operator
  sourceNamespace: openshift-marketplace
  startingCSV: observability-operator.v0.0.11-220602154408
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:openshift-operators
- kind: Group
  name: system:serviceaccounts:monitoring-stack-operator-prometheus-operator
EOF
```

The `anyuid` clusterrolebinding is necessary for the `monitoring-stack-operator-prometheus-operator` service account.

Let me know if you would like me to add more to this PR
