### ISSUE TITLE
Review resources set in components

### ISSUE THREAD

**Issue by JoaoBraveCoding** [rhobs/observability-operator#166]
Currently, our deployment of Prometheus Operator (p-o) set's the following resources:
```yaml
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
```
This is an extremely tight window of resources that p-o might hit easily, some users already reported to have hit OOM.
AFAIK we should never set limits on infrastructure components, so I suggest us removing completely the `limits`.
