### ISSUE TITLE
The API for setting resource isn't convenient

### ISSUE THREAD

**Issue by simonpasquier** [rhobs/observability-operator#279]
`.spec.resources`'s description says "Define resources requests and limits for Monitoring Stack Pods" which is misleading because the resources requests are only applied to the Prometheus resource and we have no way to define requests for Alertmanager.

Instead of

```
spec:
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
````

The API should probably look like

```
spec:
  prometheusConfig:
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
  alertmanagerConfig:
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
````

_I didn't create a ticket in JIRA but I can do later._
